export const products = [
  {
    id: 1,
    name: 'Cherry Tomato Seeds',
    category: 'Vegetable Seeds',
    price: 49,
    originalPrice: 79,
    description: 'Perfect for rooftop containers. High yield, disease resistant variety suited for Kerala climate. Harvest in 60-70 days.',
    details: 'Package contains 30 seeds. Germination rate 90%. Best sown during October to February in Kerala.',
    image: '/images/cherry-tomato.jpg',
    badge: 'Best Seller',
    inStock: true,
    rating: 4.8,
    reviews: 124,
    whatsapp: '919876543210',
  },
  {
    id: 2,
    name: 'Dwarf Banana Plant',
    category: 'Fruit Plants',
    price: 199,
    originalPrice: 299,
    description: 'Compact banana variety ideal for terrace gardens. Produces sweet fruits within 12-14 months.',
    details: 'Healthy tissue culture plant. Height at delivery: 30-40cm. Suitable for grow bags of 50L or more.',
    image: '/images/banana-plant.jpg',
    badge: 'Popular',
    inStock: true,
    rating: 4.6,
    reviews: 89,
    whatsapp: '919876543210',
  },
  {
    id: 3,
    name: 'Moringa Seeds',
    category: 'Vegetable Seeds',
    price: 39,
    originalPrice: 59,
    description: 'Drumstick tree seeds, a Kerala kitchen staple. Fast growing, nutritious and low maintenance.',
    details: 'Package contains 20 seeds. Grows well in containers with good drainage. Full sun preferred.',
    image: '/images/moringa.jpg',
    badge: 'Kerala Special',
    inStock: true,
    rating: 4.9,
    reviews: 203,
    whatsapp: '919876543210',
  },
  {
    id: 4,
    name: 'Curry Leaf Plant',
    category: 'Herbs & Spices',
    price: 89,
    originalPrice: 129,
    description: 'Fresh curry leaf plant, essential for Kerala cooking. Aromatic, fast growing and easy to maintain.',
    details: 'Healthy rooted plant in nursery bag. Height 15-25cm. Thrives in Kerala humidity.',
    image: '/images/curry-leaf.jpg',
    badge: 'Must Have',
    inStock: true,
    rating: 4.7,
    reviews: 156,
    whatsapp: '919876543210',
  },
  {
    id: 5,
    name: 'Bitter Gourd Seeds',
    category: 'Vegetable Seeds',
    price: 35,
    originalPrice: 55,
    description: 'High yielding bitter gourd variety. Excellent for vertical growing on rooftop trellises.',
    details: 'Package contains 25 seeds. Vine variety, needs support. Ready to harvest in 55-60 days.',
    image: '/images/bitter-gourd.jpg',
    badge: null,
    inStock: true,
    rating: 4.5,
    reviews: 67,
    whatsapp: '919876543210',
  },
  {
    id: 6,
    name: 'Cocopeat Grow Bag 20L',
    category: 'Grow Bags & Tools',
    price: 149,
    originalPrice: 199,
    description: 'Premium cocopeat filled grow bag. Ready to plant. Ideal for rooftop vegetable gardening.',
    details: 'Size: 12x12 inches. Pre-mixed with vermicompost and perlite. Drainage holes included.',
    image: '/images/grow-bag.jpg',
    badge: 'Ready to Use',
    inStock: true,
    rating: 4.4,
    reviews: 45,
    whatsapp: '919876543210',
  },
  {
    id: 7,
    name: 'Organic Vermicompost 1kg',
    category: 'Fertilizers',
    price: 69,
    originalPrice: 99,
    description: 'Pure organic vermicompost. Enriches soil naturally, boosts plant growth and yield.',
    details: 'Weight: 1kg. 100% organic, no chemicals. Safe for vegetables and herbs.',
    image: '/images/vermicompost.jpg',
    badge: 'Organic',
    inStock: true,
    rating: 4.8,
    reviews: 178,
    whatsapp: '919876543210',
  },
  {
    id: 8,
    name: 'Chilli Seeds — Kanthari',
    category: 'Vegetable Seeds',
    price: 45,
    originalPrice: 65,
    description: 'Authentic Kerala Kanthari chilli seeds. Extremely hot, highly aromatic. A Kerala kitchen essential.',
    details: 'Package contains 30 seeds. Best grown in full sun. Compact plant suits small containers.',
    image: '/images/kanthari.jpg',
    badge: 'Kerala Special',
    inStock: true,
    rating: 4.9,
    reviews: 312,
    whatsapp: '919876543210',
  },
]

export const categories = [
  'All',
  'Vegetable Seeds',
  'Fruit Plants',
  'Herbs & Spices',
  'Fertilizers',
  'Grow Bags & Tools',
]

export function getProductById(id) {
  return products.find(p => p.id === parseInt(id))
}

export function getProductsByCategory(category) {
  if (category === 'All') return products
  return products.filter(p => p.category === category)
}